### PR TITLE
Remove jQuery dependency for Highcharts example

### PR DESCRIPTION
**Pull request by vincent-dm**
Highcarts is not dependent on jQuery, so I altered the example to show how it can be done.

### CODE REVIEW

**Comment by gadfly361** [comment]
@vincent-dm Thanks for opening this PR!

Looks like the recipe's README has been updated, but not the source files. Please update `index.html` and `core.cljs`.  As a heads up, when I made the recommended changes, I got this runtime error `Uncaught TypeError: Highcharts.Bc is not a constructor`

**Comment by vincent-dm** [comment]
Ok, I will update it.

The error you got is probably because you didn't update the externs file.

**Comment by gadfly361** [comment]
Good catch, definitely forgot to update the externs file! After you update the source files, please squash the commits into one, and I'll get this merged in :)

**Comment by vincent-dm** [comment]
@gadfly361 I made the necessary changes, but it seems I have to do a lot of manual steps to merge the commits, while you can just do it from the Github UI [according to this page](https://help.github.com/articles/configuring-pull-request-merge-squashing/). Would you mind squashing them? Tnx!

**Comment by gadfly361** [comment]
@vincent-dm  Thanks again for the PR, just merged!

**Pull request merged**
