### PR TITLE
Add recipe for filtering tables based off of user input.

### PR DESCRIPTION
**Pull request by yatesj9**
Please let me know if the code can be improved, feel free to criticize it's how we learn. Thanks

### CODE REVIEW

**Comment by gadfly361** [comment]
Hey @yatesj9, thanks for the PR!! This will make a nice addition to the cookbook :)

The first thing I look for in a recipe is whether or not, from just the README, I can reproduce the finished product.  With that in mind, I prefer: 
* any additions to a namespace, such as `clojure.string`, to be explicitly called out in a step
* not using `:refer`, and instead using an `:alias` qualified name, such as `clojure.string/upper-case` or `reagent/atom`
* there is mention of a css file, but the code that populates that file is not included in the README (or under version control)

The other thing I look for is loosely following convention.
* `filter_value` could be renamed to `filter-value`
* can use map destructing to get id, first-name, last-name, and age from the person map
* the rc template has an exported main function that is called from index.html, which I think is a good pattern to use

Here are the index.html and core.cljs files after some of my aforementioned edits.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet" type="text/css">
  </head>
  <title>Filter Table</title>
  <body>
    <div id="app">
  </div>
    <script src="js/compiled/app.js" type="text/javascript"></script>
    <script>filter_table.core.main();</script>
  </body>
</html>
```

```clojure
(ns filter-table.core
  (:require [reagent.core :as reagent]
            [clojure.string :as string]))


(def app-state
  (reagent/atom
   [{:id 1 :first-name "Jason" :last-name "Yates" :age "34"}
    {:id 2 :first-name "Chris" :last-name "Wilson" :age "33"}
    {:id 3 :first-name "John" :last-name "Lawrence" :age "32"}
    {:id 4 :first-name "Albert" :last-name "Voxel" :age "67"}
    {:id 5 :first-name "Zemby" :last-name "Alcoe" :age "495"}]))

(defn filter-content [filterstring]
  (filter #(re-find (->> (str filterstring)
                         (string/upper-case)
                         (re-pattern))
                    (string/upper-case (:first-name %)))
          @app-state))

(defn table [myfilter]
  [:table
   [:thead
    [:tr
     [:th "First Name"]
     [:th "Last Name"]
     [:th "Age"]]]
   [:tbody
    (for [{:keys [id
                  first-name
                  last-name
                  age]} (filter-content myfilter)]
      ^{:key id}
      [:tr
       [:td first-name]
       [:td last-name]
       [:td age]])]])

(defn search-table []
  (let [filter-value (reagent/atom nil)]
    (fn []
      [:div
       [:input {:type      "text" :value @filter-value
                :on-change #(reset! filter-value (-> % .-target .-value))}]
       [table @filter-value]])))

(defn home []
  [:div
   [search-table]])

(defn ^:export main []
  (reagent/render [home]
                  (.getElementById js/document "app")))
```

**Comment by yatesj9** [comment]
Excellent feedback thank you, i've made the changes and updated the fork.
If you see anything else please let me know, this is my first contribution
to anything so i'm still learning.

**Comment by gadfly361** [comment]
Updates look great! Only thing I would add is a `.container` class to the div in home.

```clojure
(defn home []
  [:div.container
   [search-table]])
```

After adding that, I think the only thing would be to squash your commits into one.  For reference, I do this by doing an interactive rebase.

The commit right before your initial commit is `update markdown recipe, #25` with a hash of `3bb575e847d156e726a4695cebfbc0c957ebd53c`. So I would:

```
git rebase -i 3bb575e847d156e726a4695cebfbc0c957ebd53c
```

Depending on your editor, you will see something roughly similar to this:

```
pick a7eb4c6 Added filter-table
pick f7b187d Updated README with filter-table
pick 1827b8c Updated README, added bootstrap, changed to alias names from :refer, added destructuring and includex export main
pick 6b4d83e Fixed README
pick 1200c11 Added table styleing
```

You will want to change all the commits from `pick` to `squash` except for the first one.

```
pick a7eb4c6 Added filter-table
squash f7b187d Updated README with filter-table
squash 1827b8c Updated README, added bootstrap, changed to alias names from :refer, added destructuring and includex export main
squash 6b4d83e Fixed README
squash 1200c11 Added table styleing
```

Then after you get through that, it will prompt you with editing the commit message. It will try to include all of your 5 commit messages, but we don't want all that noise.

Before editing, this is what I see:

```
# This is a combination of 5 commits.
# The first commit's message is:
Added filter-table

# This is the 2nd commit message:

Updated README with filter-table

# This is the 3rd commit message:

Updated README, added bootstrap, changed to alias names from :refer, added destructuring and includex export main

# This is the 4th commit message:

Fixed README

# This is the 5th commit message:

Added table styleing

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Jason Yates <yatesj@casinorama.com>
# Date:      Tue Mar 29 10:40:05 2016 -0400
#
# rebase in progress; onto 3bb575e
# You are currently editing a commit while rebasing branch 'master' on '3bb575e'.
#
# Changes to be committed:
#	modified:   README.md
#	new file:   recipes/filter-table/README.md
#	new file:   recipes/filter-table/project.clj
#	new file:   recipes/filter-table/resources/public/index.html
#	new file:   recipes/filter-table/src/cljs/filter_table/core.cljs
#
```

However, I don't want all that, so I would change it to this:

```
Add filter-table recipe;

```

When you're don'e if you do a `git log` you should see something like this:

```
commit 260c7e38d84aadd5ed6f4fc57dc0263f2bc225f4
Author: Jason Yates <yatesj@casinorama.com>
Date:   Tue Mar 29 10:40:05 2016 -0400

    Add filter-table recipe;

commit 3bb575e847d156e726a4695cebfbc0c957ebd53c
Author: Matthew Jaoudi <gadfly361@gmail.com>
Date:   Mon Mar 14 18:17:03 2016 -0700

    update markdown recipe, #25;
```

**Comment by yatesj9** [comment]
Great info, was not aware I can squash them all together, I have done so
and pushed it up.

**Comment by gadfly361** [comment]
Woot!! Thank you :)

**Pull request merged**
