### PR TITLE
Update import render-to-string

### PR DESCRIPTION
**Pull request by piotr-yuxuan**
Since [version 0.6.1](https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#061-2017-03-10) this function has been moved.
Let me now if there is anything I can do to help the review process.

### CODE REVIEW

**Comment by gadfly361** [comment]
@piotr-yuxuan Thanks for this!

At some point, I am going to have to update the reagent-cookbook-template to use a newer version of reagent. At which point, I will be able to merge this PR in.  Is it alright with you if this sits for 'a bit' until then?

**Comment by piotr-yuxuan** [comment]
Ha ha, I feel like I competely understand how many months you mean by "a bit" ;-) cuz I would be even longer ^^ don't worry, it's perfectly OK for me :-)

**Comment by piotr-yuxuan** [comment]
Just a comment tho: I'm wondering whether it would be a good idea to put the cookbook into the main repo (à la monorepo) so it would help prevent that kind of mismatch between the code and the doc.

**Comment by piotr-yuxuan** [comment]
@gadfly361 what do you mean by "a bit" ;-) ?

**Comment by gadfly361** [comment]
@piotr-yuxuan Unfortunately, it looks like I meant quite a long time :(

Regarding your comment about the main repo, that wouldn't remove the need to update recipes when reagent updates.  The solution I am considering right now is to add a flag to the cookbook template which takes in a reagent version .. so then the cookbook recipes don't have to all be on the same version. That way, recipes can be updated individually on an as need basis (like this one).

**Pull request merged**
